/**
 * @file app.config.ts
 * @description Per-game visual identity. Generated by tools/propagate-theme.js.
 * Edit the source script and re-run to update.
 */
export const APP_CONFIG = {
  name: "Okey",
  primary: "#06B6D4",
  secondary: "#0E7490",
  splash: {
    glow: "rgba(14,116,144,0.6)",
    sallyGlow: "rgba(6,182,212,0.8)",
    pillBorder: "rgba(6,182,212,0.5)",
    pillBg: "rgba(14,116,144,0.15)",
    pillText: "#CFFAFE",
    suit: "◇",
    suit2: "◈",
  },
  slides: {
    slide2: { tint: ["rgba(6,182,212,0.55)","rgba(14,116,144,0.7)","rgba(6,30,40,0.95)"], variant: "grid" },
    slide3: { tint: ["rgba(34,211,238,0.45)","rgba(8,51,68,0.85)","rgba(6,30,40,0.95)"], variant: "spread" },
    slide4: { tint: ["rgba(245,158,11,0.45)","rgba(6,182,212,0.7)","rgba(6,30,40,0.95)"], variant: "fan" },
  },
} as const;

export type SlideVariant = 'fan' | 'scattered' | 'spread' | 'grid';
