/**
 * @file game/[roomCode].tsx
 * @description Game screen for okeyEngine. Features:
 *   - Real engine logic (deck, rules, scoring)
 *   - Online sync via Socket.IO /game namespace
 *   - AnimatedCard + haptic feedback
 *   - Player avatars, phase banner, action hints, quit confirm, winner modal
 *
 * Generated by tools/generate-game-screens.js — re-run after editing the
 * script to regenerate, or edit freely if you want game-specific UI.
 */
import React, { useReducer, useEffect, useState, useCallback, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  Alert,
  Pressable,
  Modal,
  Animated,
  Easing,
} from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { useTranslation } from 'react-i18next';
import * as Haptics from 'expo-haptics';
import { io, Socket } from 'socket.io-client';
import AppHeader from '../../src/components/AppHeader';
import AnimatedCard from '../../src/components/AnimatedCard';
import { useTheme } from '../../src/contexts/AppProviders';
import { logger } from '../../src/utils/logger';
import { APP_CONFIG } from '../../src/config/app.config';
import { SOCKET_URL } from '../../shared/api';
import * as Engine from '../../src/game/okeyEngine';

const log = logger.scoped('GameScreen');
const ME = 'p1';
const BOT_THINK_MS = 1200;

// Reusable presentational sub-components  ──────────────────────────────
function PhaseBanner({ phase, current, isMyTurn, winner, palette }: any) {
  const text = winner
    ? `🏆 ${winner.name ?? winner.winnerId ?? 'Fin'}`
    : isMyTurn
      ? '✋ À votre tour'
      : `⏳ ${current?.name ?? 'Bot'} joue…`;
  const bg = winner ? '#10B981' : isMyTurn ? APP_CONFIG.primary : 'rgba(255,255,255,0.1)';
  return (
    <View style={[styles.banner, { backgroundColor: bg, borderColor: palette.border }]}>
      <Text style={styles.bannerText}>{text}</Text>
      {phase && !winner && <Text style={styles.bannerPhase}>Phase : {phase}</Text>}
    </View>
  );
}

function AvatarRow({ players, currentId, palette }: any) {
  return (
    <View style={styles.avatarRow}>
      {players?.map((p: any) => {
        const isActive = p.id === currentId;
        return (
          <View key={p.id} style={[styles.avatarBox, isActive && { borderColor: APP_CONFIG.primary, borderWidth: 2 }]}>
            <View style={[styles.avatar, { backgroundColor: isActive ? APP_CONFIG.primary : APP_CONFIG.secondary }]}>
              <Text style={styles.avatarEmoji}>{p.isBot ? '🤖' : '👤'}</Text>
            </View>
            <Text style={[styles.avatarName, { color: palette.text }]} numberOfLines={1}>
              {p.name}
            </Text>
            <View style={styles.avatarStats}>
              <Text style={[styles.avatarScore, { color: APP_CONFIG.primary }]}>
                {p.score ?? p.chips ?? p.pairs ?? p.pairsCount ?? (p.hand?.length ?? 0)}
              </Text>
              {p.folded && <Text style={styles.avatarFold}>fold</Text>}
            </View>
          </View>
        );
      })}
    </View>
  );
}

function HelpChip({ palette, text }: any) {
  return (
    <View style={[styles.helpChip, { borderColor: palette.border }]}>
      <Ionicons name="information-circle-outline" size={14} color={palette.textSecondary} />
      <Text style={[styles.helpText, { color: palette.textSecondary }]}>{text}</Text>
    </View>
  );
}

function MoveLog({ entries, palette }: any) {
  if (!entries || entries.length === 0) return null;
  return (
    <View style={[styles.log, { borderColor: palette.border }]}>
      <Text style={[styles.logTitle, { color: palette.textSecondary }]}>📜 Derniers coups</Text>
      {entries.slice(-5).reverse().map((e: any, i: number) => (
        <Text key={i} style={[styles.logRow, { color: palette.text }]} numberOfLines={1}>
          {e.icon ?? '•'} <Text style={{ color: palette.textSecondary }}>{e.who}</Text> {e.what}
        </Text>
      ))}
    </View>
  );
}

function FeedbackToast({ message, visible, color }: any) {
  const opacity = useRef(new Animated.Value(0)).current;
  useEffect(() => {
    if (visible) {
      Animated.sequence([
        Animated.timing(opacity, { toValue: 1, duration: 180, useNativeDriver: true }),
        Animated.delay(900),
        Animated.timing(opacity, { toValue: 0, duration: 280, useNativeDriver: true }),
      ]).start();
    }
  }, [visible, message]);
  return (
    <Animated.View pointerEvents="none" style={[styles.toast, { opacity, backgroundColor: color ?? APP_CONFIG.primary }]}>
      <Text style={styles.toastText}>{message}</Text>
    </Animated.View>
  );
}

function WinnerModal({ visible, winner, onQuit, onAgain, palette }: any) {
  return (
    <Modal visible={visible} transparent animationType="fade">
      <View style={styles.modalBackdrop}>
        <LinearGradient colors={['#0A0A1A', APP_CONFIG.secondary]} style={[styles.modalCard, { borderColor: APP_CONFIG.primary }]}>
          <Text style={styles.modalEmoji}>🏆</Text>
          <Text style={styles.modalTitle}>{winner?.name ?? winner?.winnerId ?? 'Bravo !'}</Text>
          <Text style={[styles.modalSub, { color: palette.textSecondary }]}>{APP_CONFIG.name}</Text>
          <View style={{ flexDirection: 'row', gap: 12, marginTop: 20 }}>
            <TouchableOpacity onPress={onAgain} style={[styles.modalBtn, { backgroundColor: APP_CONFIG.primary }]}>
              <Text style={styles.modalBtnText}>🔄 Rejouer</Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={onQuit} style={[styles.modalBtn, { backgroundColor: 'rgba(255,255,255,0.15)' }]}>
              <Text style={styles.modalBtnText}>Quitter</Text>
            </TouchableOpacity>
          </View>
        </LinearGradient>
      </View>
    </Modal>
  );
}

// Shared base styles — extended per game-kind below
const styles = StyleSheet.create({
  banner: {
    padding: 14, borderRadius: 14, alignItems: 'center', borderWidth: 1, marginBottom: 10,
  },
  bannerText: { color: '#fff', fontSize: 15, fontFamily: 'Inter-Bold' },
  bannerPhase: { color: 'rgba(255,255,255,0.85)', fontSize: 11, fontFamily: 'Inter-SemiBold', marginTop: 3 },
  avatarRow: {
    flexDirection: 'row', justifyContent: 'space-around', marginBottom: 12,
    paddingVertical: 10, paddingHorizontal: 6,
    backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: 14,
  },
  avatarBox: { alignItems: 'center', minWidth: 60, padding: 4, borderRadius: 12 },
  avatar: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  avatarEmoji: { fontSize: 18 },
  avatarName: { fontSize: 11, fontFamily: 'Inter-SemiBold', marginTop: 4, maxWidth: 60 },
  avatarStats: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 2 },
  avatarScore: { fontSize: 13, fontFamily: 'Inter-Black' },
  avatarFold: { fontSize: 9, color: '#EF4444', fontFamily: 'Inter-Bold' },
  helpChip: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999, borderWidth: 1,
    backgroundColor: 'rgba(255,255,255,0.03)', alignSelf: 'flex-start', marginBottom: 8,
  },
  helpText: { fontSize: 11, fontFamily: 'Inter-Regular', flexShrink: 1 },
  log: { padding: 10, borderRadius: 10, borderWidth: 1, backgroundColor: 'rgba(0,0,0,0.2)', marginTop: 12 },
  logTitle: { fontSize: 11, fontFamily: 'Inter-Bold', letterSpacing: 1, marginBottom: 4 },
  logRow: { fontSize: 12, fontFamily: 'Inter-Regular', paddingVertical: 1 },
  toast: {
    position: 'absolute', top: 100, alignSelf: 'center',
    paddingHorizontal: 22, paddingVertical: 12, borderRadius: 999,
    elevation: 8, shadowColor: '#000', shadowOpacity: 0.4, shadowRadius: 8, zIndex: 100,
  },
  toastText: { color: '#fff', fontSize: 14, fontFamily: 'Inter-Black', letterSpacing: 0.5 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', alignItems: 'center', justifyContent: 'center' },
  modalCard: {
    padding: 28, borderRadius: 20, alignItems: 'center', borderWidth: 2,
    minWidth: 280, maxWidth: '85%',
  },
  modalEmoji: { fontSize: 56, marginBottom: 8 },
  modalTitle: { color: '#fff', fontSize: 24, fontFamily: 'Inter-Black', letterSpacing: 0.5 },
  modalSub: { fontSize: 13, fontFamily: 'Inter-SemiBold', marginTop: 4 },
  modalBtn: { paddingHorizontal: 22, paddingVertical: 12, borderRadius: 12 },
  modalBtnText: { color: '#fff', fontSize: 14, fontFamily: 'Inter-Bold' },
});

// Hook : online sync via Socket.IO /game (best-effort, doesn't block UI)
function useGameSocket(roomCode: string | undefined, onState: (s: any) => void) {
  const socketRef = useRef<Socket | null>(null);
  const [connected, setConnected] = useState(false);
  useEffect(() => {
    if (!roomCode) return;
    const s = io(`${SOCKET_URL}/game`, { transports: ['websocket'], timeout: 4000 });
    socketRef.current = s;
    s.on('connect', () => {
      setConnected(true);
      log.bin(`socket /game connected → join room:${roomCode}`);
      s.emit('game:join', { roomCode });
    });
    s.on('game:state', (snapshot: any) => {
      log.bout('game:state received', { phase: snapshot?.phase });
      onState(snapshot);
    });
    s.on('disconnect', () => setConnected(false));
    s.on('connect_error', (e: any) => log.warn('socket connect_error', e?.message));
    return () => { s.disconnect(); socketRef.current = null; };
  }, [roomCode]);
  const emitMove = useCallback((action: any) => {
    socketRef.current?.emit('game:action', { roomCode, action });
  }, [roomCode]);
  return { connected, emitMove };
}

const HELP_TEXT = "Formez 14 tuiles en groupes (3+ même valeur) ou suites (3+ couleur).";
const FEEDBACK_SPECIAL = "🎉 Okey !";

export default function GameScreen() {
  const { roomCode } = useLocalSearchParams<{ roomCode: string }>();
  const router = useRouter();
  const { t } = useTranslation();
  const { palette } = useTheme();

  const [state, dispatch] = useReducer(Engine.gameReducer as any, undefined, () => {
    let s: any = (Engine as any).initGame();
    const players = [
      { id: ME,  name: 'Vous',  isBot: false },
      { id: 'b1', name: 'Bot 1', isBot: true },
      { id: 'b2', name: 'Bot 2', isBot: true },
      { id: 'b3', name: 'Bot 3', isBot: true },
    ];
    for (const p of players) s = Engine.gameReducer(s, { type: 'JOIN', playerId: p.id, playerName: p.name, isBot: p.isBot } as any);
    s = Engine.gameReducer(s, { type: 'START_GAME' } as any);
    return s;
  });

  const [moveLog, setMoveLog] = useState<any[]>([]);
  const [toast, setToast] = useState<any>(null);
  const [showQuit, setShowQuit] = useState(false);
  const [phase, setPhase] = useState<'draw' | 'discard'>('draw');
  const winner = (Engine as any).getWinner ? (Engine as any).getWinner(state) : null;
  const current = (Engine as any).getCurrentPlayer ? (Engine as any).getCurrentPlayer(state) : null;
  const isMyTurn = current?.id === ME && !winner;

  const { connected, emitMove } = useGameSocket(roomCode as any, (snap) => {
    if (snap) dispatch({ type: 'SYNC_FROM_SERVER', state: snap } as any);
  });

  useEffect(() => {
    if (winner) {
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(() => {});
      setToast({ msg: FEEDBACK_SPECIAL, color: '#10B981', key: Date.now() });
      return;
    }
    if (current?.isBot && (Engine as any).botPlay) {
      const timer = setTimeout(() => {
        const action = (Engine as any).botPlay(state);
        if (action) {
          dispatch(action);
          emitMove(action);
          setMoveLog(l => [...l, { icon: '🤖', who: current.name, what: action.type.toLowerCase().replace(/_/g, ' ') }]);
        }
      }, BOT_THINK_MS);
      return () => clearTimeout(timer);
    }
  }, [state, current, winner, emitMove]);

  const me = state.players?.find((p: any) => p.id === ME);
  const myTiles = me?.hand ?? [];
  const lastDiscard = state.discardPile?.[state.discardPile.length - 1];
  const stockSize = state.stock?.length ?? 0;

  const drawFromPile = () => {
    if (!isMyTurn || phase !== 'draw') return;
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light).catch(() => {});
    const action = { type: 'DRAW_FROM_PILE', playerId: ME } as any;
    dispatch(action); emitMove(action);
    setPhase('discard');
    setMoveLog(l => [...l, { icon: '👤', who: 'Vous', what: 'a pioché' }]);
  };
  const drawFromDiscard = () => {
    if (!isMyTurn || phase !== 'draw') return;
    const action = { type: 'DRAW_FROM_DISCARD', playerId: ME } as any;
    dispatch(action); emitMove(action);
    setPhase('discard');
  };
  const discard = (tileId: string) => {
    if (!isMyTurn || phase !== 'discard') return;
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light).catch(() => {});
    const action = { type: 'DISCARD', playerId: ME, cardId: tileId } as any;
    dispatch(action); emitMove(action);
    setPhase('draw');
    setMoveLog(l => [...l, { icon: '👤', who: 'Vous', what: 'a posé' }]);
  };
  const declare = () => {
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(() => {});
    const action = { type: 'DECLARE_WIN', playerId: ME } as any;
    dispatch(action); emitMove(action);
    setToast({ msg: FEEDBACK_SPECIAL, color: '#10B981', key: Date.now() });
  };

  const restart = () => {
    let s: any = (Engine as any).initGame();
    for (const p of [{ id: ME, name: 'Vous', isBot: false }, { id: 'b1', name: 'Bot 1', isBot: true }, { id: 'b2', name: 'Bot 2', isBot: true }, { id: 'b3', name: 'Bot 3', isBot: true }]) {
      s = Engine.gameReducer(s, { type: 'JOIN', playerId: p.id, playerName: p.name, isBot: p.isBot } as any);
    }
    s = Engine.gameReducer(s, { type: 'START_GAME' } as any);
    dispatch({ type: 'SYNC_FROM_SERVER', state: s } as any);
    setMoveLog([]); setPhase('draw');
  };

  return (
    <View style={[localStyles.root, { backgroundColor: palette.bg }]}>
      <LinearGradient colors={palette.bgGradient} style={StyleSheet.absoluteFill} />
      <AppHeader title={APP_CONFIG.name} subtitle={`Salon ${roomCode ?? '—'} ${connected ? '· 🟢' : '· 🔌'}`} showBack onBack={() => setShowQuit(true)} />

      <ScrollView contentContainerStyle={localStyles.body}>
        <AvatarRow players={state.players} currentId={current?.id} palette={palette} />
        <PhaseBanner phase={`${state.phase ?? '—'} · ${isMyTurn ? phase : ''}`} current={current} isMyTurn={isMyTurn} winner={winner} palette={palette} />
        <HelpChip palette={palette} text={HELP_TEXT} />

        {/* Stock + discard */}
        <View style={localStyles.stockRow}>
          <Pressable
            onPress={drawFromPile}
            disabled={!isMyTurn || phase !== 'draw'}
            style={[localStyles.stockBox, { borderColor: APP_CONFIG.primary, opacity: (!isMyTurn || phase !== 'draw') ? 0.5 : 1 }]}
          >
            <Ionicons name="layers" size={24} color={APP_CONFIG.primary} />
            <Text style={[localStyles.stockLabel, { color: palette.text }]}>Pioche</Text>
            <Text style={[localStyles.stockCount, { color: palette.textSecondary }]}>{stockSize}</Text>
          </Pressable>
          <Pressable
            onPress={drawFromDiscard}
            disabled={!isMyTurn || phase !== 'draw' || !lastDiscard}
            style={[localStyles.stockBox, { borderColor: palette.border, opacity: (!isMyTurn || phase !== 'draw' || !lastDiscard) ? 0.5 : 1 }]}
          >
            <Text style={[localStyles.stockLabel, { color: palette.text }]}>Défausse</Text>
            {lastDiscard ? (
              <AnimatedCard value={String(lastDiscard.value)} suit={lastDiscard.suit} width={42} height={62} facing="up" />
            ) : (
              <Text style={{ color: palette.textSecondary }}>—</Text>
            )}
          </Pressable>
          <TouchableOpacity onPress={declare} style={[localStyles.declareBtn, { backgroundColor: '#10B981' }]}>
            <Text style={localStyles.declareText}>OKEY !</Text>
            <Text style={localStyles.declareSub}>Si vous avez gagné</Text>
          </TouchableOpacity>
        </View>

        <MoveLog entries={moveLog} palette={palette} />

        <Text style={[localStyles.handTitle, { color: palette.text, marginTop: 16 }]}>
          🎴 Vos tuiles ({myTiles.length}) — {phase === 'discard' ? 'tap pour défausser' : 'piochez d\'abord'}
        </Text>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={localStyles.tilesScroll}>
          {myTiles.map((c: any) => (
            <Pressable
              key={c.id}
              onPress={() => discard(c.id)}
              disabled={!isMyTurn || phase !== 'discard'}
              style={({ pressed }) => [{ opacity: !isMyTurn || phase !== 'discard' ? 0.55 : pressed ? 0.7 : 1 }]}
            >
              <AnimatedCard value={String(c.value)} suit={c.suit} width={48} height={72} facing="up" />
            </Pressable>
          ))}
        </ScrollView>
      </ScrollView>

      <FeedbackToast message={toast?.msg} visible={!!toast} color={toast?.color} key={toast?.key} />
      <WinnerModal visible={!!winner} winner={winner} onAgain={restart} onQuit={() => router.back()} palette={palette} />

      <Modal visible={showQuit} transparent animationType="fade">
        <View style={styles.modalBackdrop}>
          <View style={[styles.modalCard, { backgroundColor: palette.card, borderColor: palette.border }]}>
            <Text style={styles.modalTitle}>Quitter la partie ?</Text>
            <View style={{ flexDirection: 'row', gap: 12, marginTop: 18 }}>
              <TouchableOpacity onPress={() => setShowQuit(false)} style={[styles.modalBtn, { backgroundColor: 'rgba(255,255,255,0.15)' }]}><Text style={styles.modalBtnText}>Annuler</Text></TouchableOpacity>
              <TouchableOpacity onPress={() => { setShowQuit(false); router.back(); }} style={[styles.modalBtn, { backgroundColor: '#EF4444' }]}><Text style={styles.modalBtnText}>Quitter</Text></TouchableOpacity>
            </View>
          </View>
        </View>
      </Modal>
    </View>
  );
}

const localStyles = StyleSheet.create({
  root: { flex: 1 },
  body: { padding: 14, paddingBottom: 40 },
  stockRow: { flexDirection: 'row', gap: 10, marginVertical: 10 },
  stockBox: { flex: 1, padding: 12, borderRadius: 14, borderWidth: 2, alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.04)' },
  stockLabel: { fontSize: 11, fontFamily: 'Inter-Bold', marginTop: 6 },
  stockCount: { fontSize: 16, fontFamily: 'Inter-Black', marginTop: 2 },
  declareBtn: { flex: 1, padding: 12, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  declareText: { color: '#fff', fontSize: 16, fontFamily: 'Inter-Black', letterSpacing: 1 },
  declareSub: { color: 'rgba(255,255,255,0.85)', fontSize: 9, fontFamily: 'Inter-SemiBold', marginTop: 2 },
  handTitle: { fontSize: 13, fontFamily: 'Inter-Bold', marginBottom: 8 },
  tilesScroll: { paddingVertical: 6, paddingHorizontal: 4, gap: 6 },
});
